Repository BuildForSDG/PaytaxApp, pull requests merged in 2020-05, with the labels that each got.

#13 mvc template with MongoDB connection
  jest.config.js
  package-lock.json
  package.json
  src/app.js
  src/controllers/gatewayController.js
  src/controllers/paymentsController.js
  src/controllers/usersController.js
  src/db.js
  src/index.html
  src/index.js
  src/models/Gateway.js
  src/models/Payments.js
  src/models/Users.js
  src/routes/gateway.js
  src/routes/payments.js
  src/routes/users.js
  src/server.js
Labels: enhancement

#14 Users registration API
  package-lock.json
  package.json
  src/controllers/usersController.js
  src/models/Users.js
  src/routes/users.js
  yarn.lock
Labels: enhancement

#15 User login
  package-lock.json
  package.json
  src/config/auth.config.js
  src/config/config.js
  src/controllers/usersController.js
  src/db.js
  src/models/Users.js
  src/routes/users.js
  src/server.js
Labels: enhancement

#22 User Authorization middleware for routes
  src/config/auth.config.js
  src/config/config.js
  src/controllers/gatewayController.js
  src/controllers/usersController.js
  src/models/Gateway.js
  src/models/Users.js
Labels: enhancement

#23 Integrated payment gateway and payment history
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .prettierrc
  LICENSE
  README.md
  __tests__/app.test.js
  app.properties
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/controllers/gatewayController.js
  src/controllers/usersController.js
  src/models/Gateway.js
  src/models/Payments.js
  src/routes/gateway.js
  src/server.js
Labels: enhancement

#25 Heroku initialization setup and live endpoints
  app.properties
  package.json
Labels: bug, enhancement

#24 Get Payment History API
  src/controllers/gatewayController.js
  src/controllers/paymentsController.js
  src/models/Payments.js
  src/routes/payments.js
  src/server.js
Labels: enhancement

#26 implemented All tax types API
  src/controllers/paymentsController.js
  src/models/Payments.js
  src/routes/payments.js
Labels: enhancement

#27 Updated README.md file
  README.md
Labels: documentation

#28 Payment Receipt API
  README.md
  package-lock.json
  package.json
  src/controllers/gatewayController.js
  src/controllers/paymentsController.js
  src/models/Payments.js
  src/routes/gateway.js
  src/routes/payments.js
  src/routes/users.js
  src/server.js
Labels: enhancement

#29 User pit
  src/controllers/paymentsController.js
  src/controllers/usersController.js
  src/models/Gateway.js
  src/models/Payments.js
  src/models/Users.js
  src/routes/users.js
Labels: enhancement
